### ISSUE TITLE
Null characters in return buffer

### ISSUE THREAD

**Issue by rflaperuta** [paixaop/node-sodium#101]
Hello, I've started using the module, but when calling:

```javascript
var sodium_api = require('sodium').api;

var password_out = sodium_api.crypto_pwhash_argon2i_str(
    new Buffer(password_in),
    sodium_api.crypto_pwhash_OPSLIMIT_INTERACTIVE,
    sodium_api.crypto_pwhash_MEMLIMIT_INTERACTIVE);
```

password_out is a buffer (as it is supposed to) and contains null characters.

These are not stripped even after calling password_out.toString('ascii').

Although, printing on console using console.log strips them.

Is this by design? How to get rid of the trailing nulls?

The goal is to send the response inside a JSON object like:

```javascript
var response = {password: password_out.toString('ascii')}
```

Thanks in advance.

**Comment by richchurcher** [comment]
Isn't it by design? In the libsodium docs it says,

> The generated key has the size defined by the application, no matter what the password length is.

Assuming that the output buffer is always the same size but is null-padded, it would follow that to store the key in a database as a string, you'd need the string to be padded too. Otherwise when you regenerate the key in `crypto_pwhash_argon2i_str_verify` you'd not end up with the same result.

**Comment by jedisct1** [comment]
`crypto_pwhash_argon2i_STRBYTES` represents the maximum length of the returned string.

The string itself can be shorter, and should be trimmed after the first `\0`, even though the verification function will tolerate padding after it.

**Comment by richchurcher** [comment]
I see! Thanks, that's helpful.

**Comment by rflaperuta** [comment]
Do I need to close the Issue Before or After the PR is merged?

Thanks for the help.

**Comment by sarahscheffler** [comment]
Is it documented somewhere that you have to strip off the \0 bytes?  Or is there any interest in removing them automatically?  We just had the same issue encoding/decoding from base64 and it took us a little while to track down the error.
