### ISSUE TITLE
Possibility of async methods?

### ISSUE THREAD

**Issue by gswalden** [paixaop/node-sodium#107]
Has there been any investigation into whether we could implement asynchronous methods in this library, similar to [bcrypt](https://www.npmjs.com/package/bcrypt)? I'm hesitant to run this as a password hashing library on a production server, knowing it will block the event loop for 100-300ms every time a user attempts to login.

**Comment by paixaop** [comment]
This would be great but the lib is somewhat big and right now I have no time to do a full rewrite to support async methods. If you want to start down that path it would be awesome.

**Comment by gswalden** [comment]
Got it!
