### ISSUE TITLE
Example in crypto_aead.cc has incorrect nonce length

### ISSUE THREAD

**Issue by sarahscheffler** [paixaop/node-sodium#115]
On line 92 of node-sodium/src/crypto_aead.cc, there's example code that creates a nonce with crypto_aead_aes256gcm_KEYBYTES length.  It should be crypto_aead_aes256gcm_NPUBBYTES.  If you do it as written with KEYBYTES, you get the error
```
Error: argument npub must be 12 bytes long
    at Object.<anonymous> (/path/to/my/project/example_encrypt.js:22:25)
```

**Comment by paixaop** [comment]
FIXED. Thanks!
