### ISSUE TITLE
Possible issue with libsodium compilation on OSX

### ISSUE THREAD

**Issue by mm-tomd** [paixaop/node-sodium#116]
I couldn't get libsodium to build, it would fail on the compiler check in ./deps/libsodium/configure, i.e. checking whether the C compiler works... 

FYI I'm using OSX 10.12.4 (Sierra), npm 4.5.0, node 7.9.0, autoconf 2.69, automake 1.15, libtool 2.4.2 (compiling libsodium from tarball works fine).

Traced the issue to this conditional in the Makefile (line 33):

```
ifeq ($(UNAME_S),Darwin)
    THIS_OS = OSX
    OSX_VERSION_MIN = $(shell sw_vers -productVersion ) | awk -F '.' '{print $$1 "." $$2}'
    CFLAGS="-arch x86_64 -mmacosx-version-min=${OSX_VERSION_MIN} -O2 -g -flto"
    LDFLAGS="-arch x86_64 -mmacosx-version-min=${OSX_VERSION_MIN} -flto"
endif
```

Which resulted in weird CFLAGS and LDFLAGS in ./configure:

```
gcc "-arch x86_64 -mmacosx-version-min=10.12.4 | awk -F '.' '{print $1 "." $2}' -O2 -g -flto" -I/opt/local/include "-arch x86_64 -mmacosx-version-min=10.12.4 | awk -F '.' '{print $1 "." $2}' -flto" conftest.c  >&5
```

Updating the aforementioned Makefile conditional to the following has fixed the issue:

```
ifeq ($(UNAME_S),Darwin)
    THIS_OS = OSX
    OSX_VERSION_MIN = $(shell sw_vers -productVersion | awk -F '.' '{print $$1 "." $$2}')
    CFLAGS = -arch x86_64 -mmacosx-version-min=${OSX_VERSION_MIN} -O2 -g -flto
    LDFLAGS = -arch x86_64 -mmacosx-version-min=${OSX_VERSION_MIN} -flto
endif
```

Resulting in:

```
gcc -arch x86_64 -mmacosx-version-min=10.12 -O2 -g -flto -I/opt/local/include -arch x86_64 -mmacosx-version-min=10.12 -flto conftest.c  >&5
```

I say possible issue as my colleague has built and installed successfully on a similar setup without modification.

**Comment by mm-tomd** [comment]
So, it turns out I already had CFLAGS and LDFLAGS env vars set, makefile is overwriting then using these flags. Once I unset these vars I could install just fine (the CFLAGS and LDFLAGS set by the makefile did not get inherited by configure).

In my case Ruby Version Manager installed a config file (.rvmrc) in the users home which exports  CFLAGS, LDFLAGS and CPPFLAGS.

**Comment by joshuavial** [comment]
Thanks @mm-tomd that exactly fixed the problem I had as well.

**Comment by paixaop** [comment]
The deps/libsodium/configure comes directly from libsodium if this change fixes build issues on your Mac I would suggest you create a pull request on libsodium so it can be corrected or all.

**Comment by paixaop** [comment]
New version released can you please test it out
