### ISSUE TITLE
compilation fails due to missing autoconf, but doesn't report the cause

### ISSUE THREAD

**Issue by tfischer4765** [paixaop/node-sodium#117]
when doing a 'npm install' on the simnuki project (see https://github.com/as19git67/simnuki for details), sodium wouldn't compile because autoconf wasn't installed. However, it didn't pass the output of 'make sodium' on as expected from install.js:280-285, but failed with the following output:

https://pastebin.com/zpbQ3Xqq

A later running of npm install on a non-clean project turns them up:

```
\> sodium@1.2.3 preinstall /home/pi/simnuki/node_modules/sodium
\> node install.js --preinstall

Static libsodium was not found at /home/pi/simnuki/node_modules/sodium/deps/build/lib/libsodium so compiling libsodium from source.
autoconf is required, but wasn't found on this system
Makefile:61: recipe for target 'libsodium' failed
make: *** [libsodium] Error 1
/home/pi/simnuki/node_modules/sodium/install.js:288
            throw new Error(cmdLine + ' exited with code ' + code);
            ^

Error: make libsodium exited with code 2
    at ChildProcess.<anonymous> (/home/pi/simnuki/node_modules/sodium/install.js:288:19)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodium@1.2.3 preinstall: `node install.js --preinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sodium@1.2.3 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2017-06-14T16_14_37_197Z-debug.log
```
``` npm install --ignore-scripts && cd node_modules/sodium && make libsodium ``` produce the output 

```
Static libsodium was not found at /home/pi/simnuki/node_modules/sodium/deps/build/lib/libsodium so compiling libsodium from source.
autoconf is required, but wasn't found on this system
Makefile:61: recipe for target 'libsodium' failed
make: *** [libsodium] Error 1
```

which contains the expected information about the missing autoconf. 

#110 contains a similar problem, but in this case the output is produced as expected.

The problem occurred on a Raspberry Pi 3 running raspbian jessie of 2017-04-10 and has been consistently reproduced with node.js versions 4.2.4, 4.4.4 and 8.1.1, sodium version 1.1.12 and LATEST as of this date produced the issue.

**Comment by tfischer4765** [comment]
Note that re-running 'npm install' seems to not consistently make the output turn up, see https://pastebin.com/zwqMHSMT (this output was created before the output pasted into the issue above)

**Comment by joepie91** [comment]
I suspect that there might be a race condition introduced by [the thrown `Error`](https://github.com/paixaop/node-sodium/blob/master/install.js#L288) terminating the process before the buffer (from [the `process.stdout.write` calls](https://github.com/paixaop/node-sodium/blob/master/install.js#L280-L285)) gets a chance to write everything to `stdout`.

**Comment by paixaop** [comment]
Have you  installed autoconf?

**Comment by tfischer4765** [comment]
I didn't have autoconf installed at the time. I installed autoconf afterwards, and it works fine.

**Comment by joepie91** [comment]
@paixaop Note that the bug here is not the autoconf requirement; the bug is that the installation script does not correctly report it being missing in all cases.

**Comment by paixaop** [comment]
New version released can you please test it out

**Comment by Tosch110** [comment]
@jedau I was running into the same problem. First I noticed [this message](https://github.com/LiskHQ/lisk/tree/master#special-note-about-npm-5) 
```
Due to an issue with NPM 5.4.x and higher, node-sodium currently cannot be built. 
Therefore it is recommended to fixate the local NPM version at 5.3.x if you are running NPM 5.4.x or higher.
```

But for me it still failed. I got sure to have the [system installation process](https://github.com/LiskHQ/lisk/tree/master#system-install) complete and then just used `yarn` and it worked as expected. Hope this helps!

**Comment by jedau** [comment]
@Tosch110 I followed the exact same instructions when I did it previously, but I didn't try `npm` at `5.3.x` Will definitely try it later. Thanks for the suggestion!

**Comment by Arpita** [comment]
@jedau Running in to the same issue as part of Lisk installation. Have you managed to find a solution yet?

**Comment by devsullo** [comment]
@jedau My issue is the same.. Did you figured out?

**Comment by devsullo** [comment]
@jedau Use node V6.12.3
 `nvm install 6.12.3`

**Comment by paixaop** [comment]
I usually use npm not yarn but I did not get any autoconf errors after installing yarn with `brew install yarn --without-node`
