### ISSUE TITLE
Failing with node 6.12.0

### ISSUE THREAD

**Issue by vekexasia** [paixaop/node-sodium#124]
Hello,

Sodium cannot be built on node `6.12.0` LTS Boron. This is an excerpt of what is the stacktrace:

```
In file included from ../src/crypto_core.cc:8:0:
../src/include/node_sodium.h:153:106: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
     Nan::ForceSet(target, Nan::New<String>(#NAME).ToLocalChecked(), Nan::New<Integer>(NAME), v8::ReadOnly);
                                                                                                          ^
../src/include/crypto_core.h:30:5: note: in expansion of macro ‘NEW_INT_PROP’
     NEW_INT_PROP(crypto_core_ ## ALGO ## _OUTPUTBYTES)  
     ^
../src/crypto_core.cc:25:5: note: in expansion of macro ‘METHOD_AND_PROPS’
     METHOD_AND_PROPS(salsa208);
     ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/include/node_sodium.h:20,
                 from ../src/crypto_core.cc:8:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
/home/andrea/node_modules/sodium/install.js:288
            throw new Error(cmdLine + ' exited with code ' + code);
            ^

Error: make nodesodium exited with code null
    at ChildProcess.<anonymous> (/home/andrea/node_modules/sodium/install.js:288:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
```

**Comment by vekexasia** [comment]
Actually it fails also with `6.11.0` and `6.10.x`.

**Comment by shideneyu** [comment]
Same issue on node ´6.9´

**Comment by vekexasia** [comment]
just issue `npm i nan@2.7.0` and insert it in your package as `dependency` with the <2.8.0 flag or =2.7.0 so that 2.8.0 does not get installed.

**Comment by shideneyu** [comment]
I deleted my previosu comment because I was not sure of my version anymore. But yeah I confirm that I got the same issue; and thanks will do

**Comment by anibali** [comment]
I'm having the same problem with Node v8.1.2 on Ubuntu 16.04, and Node v8.9.1 on Alpine Linux. Building the fork at https://github.com/LiskHQ/node-sodium which fixes nan to v2.2.1 works.

**Comment by chiedo** [comment]
Hey @vekexasia it doesn't seem like the repo owner is that active... Do you want to launch an official fork and deploy it as sodium-2 or something to npm?

**Comment by paixaop** [comment]
Sorry guys, will merge today.

**Comment by chiedo** [comment]
Thanks @paixaop! :)

**Comment by chiedo** [comment]
Can you update npm @paixaop ? Or if you want me to start updating npm for you, let me know.

**Comment by paixaop** [comment]
Adding support for libsodium 1.0.15 and fixing this. should be uploaded soon. If you need before check the libsodium-1.0.15 branch. it's already fixed there.

**Comment by chiedo** [comment]
Thanks @paixaop you are the man!

**Comment by anibali** [comment]
@paixaop I've discovered the root cause of this issue. You can find details and fix in https://github.com/paixaop/node-sodium/pull/128
