### ISSUE TITLE
Can't resolve library on Mac OS X

### ISSUE THREAD

**Issue by deweller** [paixaop/node-sodium#130]
After installing, I get this error when I try to run npm build:

`Module not found: Error: Can't resolve '../build/Release/sodium' in '/path/to/app/node_modules/sodium/lib'`

**Comment by mpc20001** [comment]
Having the same problem.

**Comment by deweller** [comment]
I wasn't able to figure this out.  I gave up and used something else.

**Comment by mpc20001** [comment]
What did you end up using?

**Comment by whaus7** [comment]
Also having this issue and I really need to use sodium.. 

./node_modules/sodium/lib/keys/dh-key.js
Module not found: Can't resolve '../../build/Release/sodium' in '/Users/whausman/PhpstormProjects/xchange/node_modules/sodium/lib/keys'

Pleeease help :)

**Comment by mpc20001** [comment]
I ended up using js-nacl - worked great.

**Comment by whaus7** [comment]
yeah? Thanks dude, appreciate it. Similar to use as sodium? Trying to use some existing code for the encryption parts since I'm a bit noob in that area

**Comment by whaus7** [comment]
Seems to be working without a hitch! 👍  Thanks @mpc20001 !

**Comment by mpc20001** [comment]
Congrats!
