### ISSUE TITLE
Allow passing in a path for private key

### ISSUE THREAD

**Issue by mjsalinger** [paixaop/node-sodium#15]
When using key encryption/decryption via box, secure-box, etc, it would be beneficial to provide a file path to be used for the location of the private key.  The private key should then be loaded via the C++ binding and deleted from memory immediately after use, allowing the private key to stay resident in memory for as little time as possible (to minimize exposure to heartbleed-like vulnerabilities).

**Comment by squirrelsama** [comment]
To preserve the simplicity of this project, I would advocate that the project does not include this change. Not for security reasons. Just for simplicity.

This is certainly a fun topic of conversation, but I feel it's far out of scope for this project. From my perspective, the high-level API is already too much.

**Comment by paixaop** [comment]
True I've been thinking about splitting the high level out as well.
