### ISSUE TITLE
make libsodium exited with code 2, pwhash_argon2i fails

### ISSUE THREAD

**Issue by jespertheend** [paixaop/node-sodium#152]
Hi,

Please see https://github.com/jedisct1/libsodium/issues/878
This appears to be a known issue with sodium and currently the solution is to build sodium from the latest stable release. Though I'm not really sure how I would go about doing that when using `npm install sodium`

**Comment by rawr51919** [comment]
That particular issue seems to have been fixed for a while now. Should this be closed because of it?

**Comment by jespertheend** [comment]
Hmm I can't quite remember how I got this issue in the first place now. Though when I posted this issue https://github.com/jedisct1/libsodium/issues/878 was already closed. I'll see if I can still replicate this and let you know.

**Comment by jespertheend** [comment]
This seems to be fixed now.
