### ISSUE TITLE
Compiling on ARM fails

### ISSUE THREAD

**Issue by seriousmumbo** [paixaop/node-sodium#25]
Libsodium fails to compile on ARM.  I ran 'node-gyp configure' and 'node-gyp build'.  I've copypasta'd the entire thing below, but I think the relevant part is this:

crypto_onetimeauth/poly1305/donna/portable-jane.h:674: unable to emulate 'TI'

Any ideas?

    root@7el8ql:~/node-sodium# node-gyp configure
    gyp info it worked if it ends with ok
    gyp info using node-gyp@0.10.10
    gyp info using node@0.10.25 | linux | arm
    gyp info spawn python
    gyp info spawn args [ '/usr/share/node-gyp/gyp/gyp',
    gyp info spawn args   'binding.gyp',
    gyp info spawn args   '-f',
    gyp info spawn args   'make',
    gyp info spawn args   '-I',
    gyp info spawn args   '/root/node-sodium/build/config.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/usr/share/node-gyp/addon.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/usr/include/nodejs/common.gypi',
    gyp info spawn args   '-Dlibrary=shared_library',
    gyp info spawn args   '-Dvisibility=default',
    gyp info spawn args   '-Dnode_root_dir=/usr/include/nodejs',
    gyp info spawn args   '-Dmodule_root_dir=/root/node-sodium',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.' ]
    gyp info ok

    root@7el8ql:~/node-sodium# node-gyp build
    gyp info it worked if it ends with ok
    gyp info using node-gyp@0.10.10
    gyp info using node@0.10.25 | linux | arm
    gyp info spawn make
    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    make: Entering directory `/root/node-sodium/build'
      CC(target) Release/obj.target/libsodium/deps/libsodium-0.4.5/src/libsodium/crypto_auth/cr.o
      CC(target) Release/obj.target/libsodium/deps/libsodium-0.4.5/src/libsodium/crypto_auth/hmauth_hmacsha256_api.o
      CC(target) Release/obj.target/libsodium/deps/libsodium-0.4.5/src/libsodium/crypto_auth/hmref/hmac_hmacsha256.o
      CC(target) Release/obj.target/libsodium/deps/libsodium-0.4.5/src/libsodium/crypto_auth/hmref/verify_hmacsha256.o
      CC(target) Release/obj.target/libsodium/deps/libsodium-0.4.5/src/libsodium/crypto_auth/hm56/auth_hmacsha512256_api.o
      CC(target) Release/obj.target/libsodium/deps/libsodium-0.4.5/src/libsodium/crypto_auth/hm56/ref/hmac_hmacsha512256.o
      CC(target) Release/obj.target/libsodium/deps/libsodium-0.4.5/src/libsodium/crypto_auth/hm56/ref/verify_hmacsha512256.o
      CC(target) Release/obj.target/libsodium/deps/libsodium-0.4.5/src/libsodium/crypto_box/cry
      CC(target) Release/obj.target/libsodium/deps/libsodium-0.4.5/src/libsodium/crypto_box/curalsa20poly1305/box_curve25519xsalsa20poly1305_api.o
      CC(target) Release/obj.target/libsodium/deps/libsodium-0.4.5/src/libsodium/crypto_box/curalsa20poly1305/ref/after_curve25519xsalsa20poly1305.o
      CC(target) Release/obj.target/libsodium/deps/libsodium-0.4.5/src/libsodium/crypto_box/curalsa20poly1305/ref/before_curve25519xsalsa20poly1305.o
      CC(target) Release/obj.target/libsodium/deps/libsodium-0.4.5/src/libsodium/crypto_box/curalsa20poly1305/ref/box_curve25519xsalsa20poly1305.o
      CC(target) Release/obj.target/libsodium/deps/libsodium-0.4.5/src/libsodium/crypto_box/curalsa20poly1305/ref/keypair_curve25519xsalsa20poly1305.o
      CC(target) Release/obj.target/libsodium/deps/libsodium-0.4.5/src/libsodium/crypto_core/hsf2/core_hsalsa20.o
      CC(target) Release/obj.target/libsodium/deps/libsodium-0.4.5/src/libsodium/crypto_core/hsre_hsalsa20_api.o
      CC(target) Release/obj.target/libsodium/deps/libsodium-0.4.5/src/libsodium/crypto_core/sa/core_salsa20.o
      CC(target) Release/obj.target/libsodium/deps/libsodium-0.4.5/src/libsodium/crypto_core/sae_salsa20_api.o
      CC(target) Release/obj.target/libsodium/deps/libsodium-0.4.5/src/libsodium/crypto_core/saef/core_salsa2012.o
      CC(target) Release/obj.target/libsodium/deps/libsodium-0.4.5/src/libsodium/crypto_core/saore_salsa2012_api.o
      CC(target) Release/obj.target/libsodium/deps/libsodium-0.4.5/src/libsodium/crypto_core/saf/core_salsa208.o
      CC(target) Release/obj.target/libsodium/deps/libsodium-0.4.5/src/libsodium/crypto_core/sare_salsa208_api.o
      CC(target) Release/obj.target/libsodium/deps/libsodium-0.4.5/src/libsodium/crypto_genericto_generichash.o
      CC(target) Release/obj.target/libsodium/deps/libsodium-0.4.5/src/libsodium/crypto_generice2/generichash_blake2_api.o
      CC(target) Release/obj.target/libsodium/deps/libsodium-0.4.5/src/libsodium/crypto_generice2/ref/blake2b-ref.o
      CC(target) Release/obj.target/libsodium/deps/libsodium-0.4.5/src/libsodium/crypto_generice2/ref/generichash_blake2b.o
      CC(target) Release/obj.target/libsodium/deps/libsodium-0.4.5/src/libsodium/crypto_hash/cr.o
      CC(target) Release/obj.target/libsodium/deps/libsodium-0.4.5/src/libsodium/crypto_hash/sh_sha256_api.o
      CC(target) Release/obj.target/libsodium/deps/libsodium-0.4.5/src/libsodium/crypto_hash/shhash_sha256.o
      CC(target) Release/obj.target/libsodium/deps/libsodium-0.4.5/src/libsodium/crypto_hash/sh_sha512_api.o
      CC(target) Release/obj.target/libsodium/deps/libsodium-0.4.5/src/libsodium/crypto_hash/shhash_sha512.o
      CC(target) Release/obj.target/libsodium/deps/libsodium-0.4.5/src/libsodium/crypto_hashblo6/ref/blocks_sha256.o
      CC(target) Release/obj.target/libsodium/deps/libsodium-0.4.5/src/libsodium/crypto_hashblo6/hashblocks_sha256_api.o
      CC(target) Release/obj.target/libsodium/deps/libsodium-0.4.5/src/libsodium/crypto_hashblo2/ref/blocks_sha512.o
      CC(target) Release/obj.target/libsodium/deps/libsodium-0.4.5/src/libsodium/crypto_hashblo2/hashblocks_sha512_api.o
      CC(target) Release/obj.target/libsodium/deps/libsodium-0.4.5/src/libsodium/crypto_onetimeto_onetimeauth.o
      CC(target) Release/obj.target/libsodium/deps/libsodium-0.4.5/src/libsodium/crypto_onetime1305/onetimeauth_poly1305.o
      CC(target) Release/obj.target/libsodium/deps/libsodium-0.4.5/src/libsodium/crypto_onetime1305/onetimeauth_poly1305_api.o
      CC(target) Release/obj.target/libsodium/deps/libsodium-0.4.5/src/libsodium/crypto_onetime1305/onetimeauth_poly1305_try.o
      CC(target) Release/obj.target/libsodium/deps/libsodium-0.4.5/src/libsodium/crypto_onetime1305/53/auth_poly1305_53.o
      CC(target) Release/obj.target/libsodium/deps/libsodium-0.4.5/src/libsodium/crypto_onetime1305/53/verify_poly1305_53.o
      CC(target) Release/obj.target/libsodium/deps/libsodium-0.4.5/src/libsodium/crypto_onetime1305/donna/auth_poly1305_donna.o
    In file included from ../deps/libsodium-0.4.5/src/libsodium/crypto_onetimeauth/poly1305/donoly1305_donna.c:6:0:
    ../deps/libsodium-0.4.5/src/libsodium/crypto_onetimeauth/poly1305/donna/portable-jane.h:674: unable to emulate 'TI'
    ../deps/libsodium-0.4.5/src/libsodium/crypto_onetimeauth/poly1305/donna/portable-jane.h: In 'shr128_pair':
    ../deps/libsodium-0.4.5/src/libsodium/crypto_onetimeauth/poly1305/donna/portable-jane.h:747ng: left shift count >= width of type [enabled by default]
    ../deps/libsodium-0.4.5/src/libsodium/crypto_onetimeauth/poly1305/donna/portable-jane.h: In 'hi128':
    ../deps/libsodium-0.4.5/src/libsodium/crypto_onetimeauth/poly1305/donna/portable-jane.h:767ng: right shift count >= width of type [enabled by default]
    make: *** [Release/obj.target/libsodium/deps/libsodium-0.4.5/src/libsodium/crypto_onetimeau05/donna/auth_poly1305_donna.o] Error 1
    make: Leaving directory `/root/node-sodium/build'
    gyp ERR! build error
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
    gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
    gyp ERR! System Linux 3.8.13-bone50
    gyp ERR! command "nodejs" "/usr/bin/node-gyp" "build"
    gyp ERR! cwd /root/node-sodium
    gyp ERR! node -v v0.10.25
    gyp ERR! node-gyp -v v0.10.10
    gyp ERR! not ok

**Comment by r-arias** [comment]
Does anyone have a hint for me how to fix this?

**Comment by jonasfj** [comment]
this sounds like a libsodium issue, not a node-sodium issue... Or maybe it part of how libsodium gets build...
Either way, I don't really have any good ideas. Perhaps start with getting libsodium to build...

Is this arm or i686 too? And any suggestions for how to reproduce, maybe supply a vagrant box...

**Comment by paixaop** [comment]
can you  try the develop branch?
