### ISSUE TITLE
Can't build on Linux 3.2.0-23-generic-pae

### ISSUE THREAD

**Issue by bezreyhan** [paixaop/node-sodium#34]
I'm getting this error when I try to 'npm install sodium'. I do have libsodium installed and other applications are able to use it.

npm ERR! sodium@1.0.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sodium@1.0.13 install script.
npm ERR! This is most likely a problem with the sodium package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sodium
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.2.0-23-generic-pae
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "sodium"

any ideas?

**Comment by bezreyhan** [comment]
The problem seems to be with node-gyp. I'm getting this error now: 

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Linux 3.2.0-23-generic-pae

**Comment by bezreyhan** [comment]
I just cloned node-sodium, ran:
node-gyp clean
node-gyp configure
node-gyp build

I got the pretty much the sam error: 
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Linux 3.2.0-23-generic-pae
gyp ERR! command "node" "/usr/bin/node-gyp" "build"
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok

**Comment by paixaop** [comment]
can you try the develop branch?

**Comment by bezreyhan** [comment]
I'm getting this:

gyp: /home/vagrant/node-sodium/deps/libsodium.gyp not found (cwd: /home/vagrant/node-sodium) while loading dependencies of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Linux 3.2.0-23-generic-pae
gyp ERR! command "node" "/usr/bin/node-gyp" "configure"
gyp ERR! cwd /home/vagrant/node-sodium
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 

In the develop branch node-sodium/deps has libsodium.gyp.in but not libsodium.gyp

**Comment by bezreyhan** [comment]
I copy and pasted the libsodium.gyp from master just to give it a shot:

make: Entering directory `/home/vagrant/projects/round-node/node_modules/sodium/build'
make: Warning: File `sodium.target.mk' has modification time 7.5e+02 s in the future
make: *** No rule to make target `Release/obj.target/libsodium/deps/libsodium-1.0.0/src/libsodium/crypto_aead/chacha20poly1305/sodium/aead_chacha20poly1305.o', needed by `Release/obj.target/deps/sodium.a'.  Stop.
make: Leaving directory `/home/vagrant/projects/round-node/node_modules/sodium/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Linux 3.2.0-23-generic-pae
gyp ERR! command "node" "/usr/bin/node-gyp" "build"
gyp ERR! cwd /home/vagrant/projects/round-node/node_modules/sodium
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
vagrant@precise32:~/projects/round-node/node_modules/sodium$

**Comment by paixaop** [comment]
Please run make configure to create the necessary files

**Comment by bezreyhan** [comment]
That's the error I got when I ran node-gyp configure

when I run make configure I get: ./autogen.sh: 13: ./autogen.sh: libtoolize: not found

When I copy and pasted the libsodium.gyp file from master I was able to configure but then I got the last error that I posted in my last comment.

**Comment by bezreyhan** [comment]
Ok, I got it to build but I had to first download libtoolize and automake.

Is there a way to list those packages in the dependencies so that they download automatically?
Also, do you know how I can get this to work with NPM?

Thanks

**Comment by paixaop** [comment]
You need to install autotools and autoconf in your system. This is a 
requirement of libsodium itself

on mac you can run

|brew install automake|

or

|sudo port install automake autoconf libtool


|

**Comment by paixaop** [comment]
Should work with npm now.

**Comment by bezreyhan** [comment]
I had compiled libsodium from source so I was missing those packages.

npm install does work now. Thanks for the help!
