### ISSUE TITLE
should bind to secretbox_easy not secretbox

### ISSUE THREAD

**Issue by dominictarr** [paixaop/node-sodium#44]
`secretbox` take a buffer 32 bytes too large and zeros the first 16. that is just an internal implementation detail... probably it's so you have some room to write a length field in there or something...
This only makes sense in C though, for use in any other language we want `secretbox_easy`

**Comment by dominictarr** [comment]
I'll make a pull request.

**Comment by dominictarr** [comment]
can you npm publish this?

**Comment by paixaop** [comment]
done. this pull request is now included in the 1.0.20. Thanks!!!
