### ISSUE TITLE
Installing on Windows?

### ISSUE THREAD

**Issue by paragonie-scott** [paixaop/node-sodium#51]
Running `npm install sodium` doesn't work on Windows. Essentially, it says `make not found` and aborts.

This will *probably* require installing libsodium separately first (do we need to install libsodium-net and grab the dll?). I don't know.

**Comment by paixaop** [comment]
Yes

Today the install process requires automake and make tools. You can try to compile under Cygwin. If you port the build stage to windows I will merge it in. 

Pedro

**Comment by squirrelsama** [comment]
@paragonie-scott I also have a need for MingGW-less Windows builds. Does it sound unreasonable to pull down the pre-built Windows binaries from https://download.libsodium.org/libsodium/releases/ ? Do you know of any other native modules that do this? It might be against the node-gyp way to not compile from source, but it might be simpler to accomplish what we need that way. I'm gonna take a look at either anyway and see what I come up with.

**Comment by paixaop** [comment]
Today the automake is a way around getting the right compilation defines so that libsodium compiles in each platform. If you get libsodium to compile on your windows machine send me a copy of your Makefile, and I'll see if I can include it in the compilation process

**Comment by tommitytom** [comment]
I notice this has been closed, yet there appears to be no clear way on how to get this working on Windows.  Has this actually been resolved?

**Comment by paixaop** [comment]
You can now use a binary distribution of the libsodium library and node sodium will bypass sodium compilation on windows and other platforms.
Check the [Manual Build](https://github.com/paixaop/node-sodium#manual-build) section of the Readme

**Comment by creshal** [comment]
NPM deletes the sodium folder between failed builds, so if the automatic build fails, you never get a folder to drop the binary distribution into. So this doesn't really work. Is there a way to specify a binary folder in an outside location?

**Comment by paixaop** [comment]
@creshal for the time being you can download the source from github and run make manually.

**Comment by creshal** [comment]
That compiles, after some changes to the makefile (I'll make a pull request for that once everything works), but now Node throws a "cannot find module" error when trying to load sodium or run Mocha:

    Error: Das angegebene Modul wurde nicht gefunden.
    \\?\C:\Users\creshal\Desktop\foo\app\node_modules\sodium\build\Release\sodium.node
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\creshal\Desktop\foo\app\node_modules\sodium\lib\sodium.js:16:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)

The file definitely exists, however.
