### ISSUE TITLE
simplify install dependencies

### ISSUE THREAD

**Issue by dominictarr** [paixaop/node-sodium#52]
this is complicated to build because it needs automake, would it be possible to remove these extra deps so that it installs with stock node-gyp? https://github.com/Level/leveldown is able to compile with just node-gyp, which makes it easy to use.

**Comment by squirrelsama** [comment]
I second this motion. @dominictarr Toss up a PR -- I'm going to see about the windows build process issue.

**Comment by paixaop** [comment]
please refer to #51

**Comment by dominictarr** [comment]
sorry, I did not include enough detail in my issue. I should have said that automake is a problem building on osx. but as i look deeper into it, i see that automake is a part of libsodium, not node-sodium, so is harder to remove.

**Comment by jedisct1** [comment]
automake (and other autotools) are not needed to build Sodium. Releases tarballs have all the required script already built.

**Comment by paixaop** [comment]
Correct. Lib sodium uses automake. But on osx you can easily install the toolset with 'brew install automake'



Pedro

**Comment by paixaop** [comment]
Right now libaodium is statically linked into nose sodium so can't use the release versions. 
If you add support for dynamic link I will integrate it. 

Pedro

**Comment by jedisct1** [comment]
`automake` is not needed, even on OSX.

**Comment by dominictarr** [comment]
without automake, you get an error cannot find "libtoolize"

https://github.com/paixaop/node-sodium/blob/master/deps/libsodium/autogen.sh#L7-L16

is there a way around that?

**Comment by jedisct1** [comment]
Do not use the development code in Git!

Use the release tarballs, available [here](https://download.libsodium.org/libsodium/releases/) and [here](https://github.com/jedisct1/libsodium/releases) (the .tar.gz files, not the zip files).

You don't need to run `autogen.sh`.
