### ISSUE TITLE
Calling box seal functions

### ISSUE THREAD

**Issue by perfaram** [paixaop/node-sodium#54]
I don't think I can do it, but still : is there a way to call `crypto_box_seal*` functions from JS ?
Thanks !

**Comment by paixaop** [comment]
these functions are not yet supported in node-sodium, and it will take me some time to do it. If you look over sodium.cc file and check out how the other functions are implemented it should be really straight forward to do it your self. Create a pull request and write the tests and if everything checks out i'll merge it in.

**Comment by perfaram** [comment]
OK, thanks ! However, I choose to use another lib (a emscripten-compiled version of libsodium), so I have all the functions right now. Sorry !
