### ISSUE TITLE
crypto_generichash

### ISSUE THREAD

**Issue by KenanSulayman** [paixaop/node-sodium#57]
Hi,

is there any particular reason no binding for crypto_generichash (blake2b) exists?

Thanks

**Comment by dominictarr** [comment]
just because no one has made the PR yet

**Comment by paixaop** [comment]
implemented in the new branch  https://github.com/paixaop/node-sodium/tree/libsodium-1.0.8-update try it out and let me know if it works

**Comment by KenanSulayman** [comment]
Nice, thanks. Will give it a shot!
