### ISSUE TITLE
FreeBSD requires gmake

### ISSUE THREAD

**Issue by lgrahl** [paixaop/node-sodium#62]
Currently, ``make`` is being used in [package.json](https://github.com/paixaop/node-sodium/blob/f21f268105eff0a82817a5ac0fb323a4ab219828/package.json) for the scripts *test* and *preinstall*. However, this results in a syntax error on FreeBSD:

```
"Makefile", line 14: Missing dependency operator
"Makefile", line 17: Need an operator
```

Manually replacing ``make`` with ``gmake`` works as a temporary workaround on FreeBSD but most certainly is not the solution.

**Comment by paixaop** [comment]
Try the new branch https://github.com/paixaop/node-sodium/tree/libsodium-1.0.8-update which relies completely on lib sodium's build system which should be solid on you platform.
