### ISSUE TITLE
Can't install on OSX Yosemite: `libtoolize: command not found`

### ISSUE THREAD

**Issue by benbuckman** [paixaop/node-sodium#63]
Installing on OSX Yosemite (10.10.5), I get this error:

> sodium@1.0.22 preinstall /Users/ben/dev/shared/node-sodium
> make
>
> ./autogen.sh: line 13: libtoolize: command not found
> make: *** [configure] Error 127

I can `brew install libtool`, but this makes it hard to share as a standard module. Is it possible to use more generic build tools?

Thank you

**Comment by benbuckman** [comment]
Also, `brew info libtool` says,

> In order to prevent conflicts with Apple's own libtool we have prepended a "g"
so, you have instead: glibtool and glibtoolize.

So this would still not work.

**Comment by benbuckman** [comment]
Ah, I see https://github.com/paixaop/node-sodium/issues/52#issuecomment-131356621 now. Will close.

**Comment by benbuckman** [comment]
Re-opening: `npm install sodium` produces the same error. Please advise.
Thank you

**Comment by paixaop** [comment]
I always compile on OSX with brew install automake, have you tried that?

On Fri, Nov 6, 2015 at 3:03 PM, Ben Buckman <notifications@github.com>
wrote:

> Re-opening: npm install sodium produces the same error. Please advise.
> Thank you
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/paixaop/node-sodium/issues/63#issuecomment-154517771>.
>



-- 
Do It Right or Don't Do It At All!

**Comment by paixaop** [comment]
try the new branch https://github.com/paixaop/node-sodium/tree/libsodium-1.0.8-update and let me know if it works
