### ISSUE TITLE
avoid copies in: crypto_secretbox, add binding to crypto_secretbox_detached

### ISSUE THREAD

**Issue by dominictarr** [paixaop/node-sodium#66]
I have realized that the current implementation allocates more memory in `crypto_secretbox`
https://github.com/paixaop/node-sodium/blob/master/sodium.cc#L575-L603

`crypto_secretbox` expects the message to start after 32 zero bytes. this seems strange, but the rationale is that then you can use the same buffer for the plaintext input and the ciphertext output, if you want to painstakingly manage your memory. In this node binding new buffers are allocated for the return value, but in the c code, you must pass in a pointer to the buffer that you would like the return value written into. this gives the option to use the same buffer as the input and the output.

If you are writing modular code, then you don't know where there input will come from, and so getting a buffer with an extra 32 bytes and the start seems unlikely. However, there is also a method `crypto_secretbox_detached` and `crypto_secretbox_open_detached` which support having the `mac` in a different buffer.

That is probably a more practical optimization, in fact, I already use that here https://github.com/dominictarr/pull-box-stream/blob/master/index.js#L11-L16 although at the time of writing that code I wasn't aware that sodium implemented `crypto_secretbox_open_detached`.

This is something that needs to happen at some point, putting this here as a reminder for my self, unless someone else wants to take it ;)

**Comment by paixaop** [comment]
crypto_secretbox_open_detached implemented in new branch that moves to libsodium 1.0.10 and implements a bunch of new functions see https://github.com/paixaop/node-sodium/tree/split-sodium
