### ISSUE TITLE
Can't figure out how to use Scrypt, no documentation

### ISSUE THREAD

**Issue by peradym** [paixaop/node-sodium#69]
I have tried digging through the header files in order to determine how to use Scrypt without any success. I did find this:
```
int crypto_pwhash_scryptsalsa208sha256_str(char out[crypto_pwhash_scryptsalsa208sha256_STRBYTES],
                                           const char * const passwd,
                                           unsigned long long passwdlen,
                                           unsigned long long opslimit,
                                           size_t memlimit);
```
But I cannot figure out how to use it. Node.js returns "is not a function". I am using `var sodium = require("sodium").api;`

How can I use the Scrypt implementation with this library?

**Comment by paixaop** [comment]
implemented in https://github.com/paixaop/node-sodium/tree/libsodium-1.0.8-update
