### ISSUE TITLE
BLAKE2b?

### ISSUE THREAD

**Issue by NodeGuy** [paixaop/node-sodium#83]
Why is the default hashing algorithm `SHA-512` instead of the default (`BLAKE2b`) used by [Sodium](https://download.libsodium.org/libsodium/content/hashing/generic_hashing.html)?

**Comment by paixaop** [comment]
@NodeGuy generic hash just calls Lib Sodium Genrichash so it should use the same defaults.

**Comment by NodeGuy** [comment]
OK thanks.
