### ISSUE TITLE
Fails to install on node 6.6

### ISSUE THREAD

**Issue by howardkitto** [paixaop/node-sodium#85]
Hi

I've been trying to install sodium on osx but get this error.

Libtool is required apparently

Thanks

> sodium@1.1.15 preinstall /Users/howardkitto/Projects/synapsjlincdemo/node_modules/.staging/sodium-e268ede4
> node install.js --preinstall

Static libsodium was not found at /Users/howardkitto/Projects/synapsjlincdemo/node_modules/.staging/sodium-e268ede4/deps/build/lib/libsodium so compiling libsodium from source.
libtool is required, but wasn't found on this system
make: *** [libsodium] Error 1
/Users/howardkitto/Projects/synapsjlincdemo/node_modules/.staging/sodium-e268ede4/install.js:279
            throw new Error(cmdLine + ' exited with code ' + code);
            ^

Error: make libsodium exited with code 2
    at ChildProcess.<anonymous> (/Users/howardkitto/Projects/synapsjlincdemo/node_modules/.staging/sodium-e268ede4/install.js:279:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "sodium"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! sodium@1.1.15 preinstall: `node install.js --preinstall`
npm ERR! Exit status 1

**Comment by dsshap** [comment]
+1 here

**Comment by richchurcher** [comment]
@howardkitto @dsshap To get past this, try:

```shell
brew install libtool autoconf automake
```

If you're a Homebrew user, obviously. I'm not really a Mac person but I did have to do this to use libsodium at work. I believe this is because XCode doesn't provide GNU versions of autotools.

**Comment by howardkitto** [comment]
Thanks - this fixed it perfectly
