### ISSUE TITLE
use vector based tests

### ISSUE THREAD

**Issue by dominictarr** [paixaop/node-sodium#87]
would you take a PR to use my chloride-test module?

https://www.npmjs.com/package/chloride-test

it is a reusable test suite for a library implementing the node-sodium low level api,
and is also used to test https://github.com/dominictarr/sodium-browserify-tweetnacl and https://github.com/dominictarr/sodium-browserify

It caught https://github.com/paixaop/node-sodium/commit/805b6f521db3f5049b4e961a6304b8b2ded63eec#commitcomment-19350734 which didn't have test coverage in this library

Also, it means that we make assertions that a function returns the correct cyphertext. Since most of the sodium api is deterministic (except keypair() and randombytes(), obviously) then we can generate a test suite, and then make sure that an implementation returns exactly those values.

**Comment by dominictarr** [comment]
oh, and also, since the implementations of encryption and decryption both depend on key stream generation, it means a could be introduced that would still preserve `plaintext == decrypt(encrypt(plaintext))` but would in fact return a cyphertext which is incompatible with another implemention, hence, vector based tests are essential.

I generated these vectors from `node-sodium@1.0.22` output, since I could not find any official vectors.

**Comment by paixaop** [comment]
Let me check into it, on first sight it seems like a great idea. Thank you for your suggestion.
